-- LSAC/LawHub integration persistence tables.
-- Stores provider snapshots, test instance payloads, logging audit trail,
-- and normalized content module projections.

create table public.lsac_student_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  student_coaching_id text not null,
  email text,
  first_name text,
  last_name text,
  linked boolean,
  subscription_type text,
  fetched_at timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb
);

create index lsac_student_snapshots_user_id_idx
  on public.lsac_student_snapshots (user_id);
create index lsac_student_snapshots_student_coaching_id_idx
  on public.lsac_student_snapshots (student_coaching_id);
create index lsac_student_snapshots_fetched_at_idx
  on public.lsac_student_snapshots (fetched_at desc);

create table public.lsac_test_instances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  student_coaching_id text not null,
  test_instance_id text not null,
  test_id text,
  is_completed boolean,
  start_date timestamptz,
  end_date timestamptz,
  updated_at timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb,
  unique (student_coaching_id, test_instance_id)
);

create index lsac_test_instances_user_id_idx
  on public.lsac_test_instances (user_id);
create index lsac_test_instances_student_coaching_id_idx
  on public.lsac_test_instances (student_coaching_id);
create index lsac_test_instances_updated_at_idx
  on public.lsac_test_instances (updated_at desc);

create table public.lsac_log_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  student_coaching_id text not null,
  event_type text not null,
  status_code int,
  success boolean not null default false,
  error_message text,
  request_payload jsonb not null default '{}'::jsonb,
  response_payload jsonb,
  created_at timestamptz not null default now()
);

create index lsac_log_events_user_id_idx
  on public.lsac_log_events (user_id);
create index lsac_log_events_student_coaching_id_idx
  on public.lsac_log_events (student_coaching_id);
create index lsac_log_events_event_type_idx
  on public.lsac_log_events (event_type);
create index lsac_log_events_created_at_idx
  on public.lsac_log_events (created_at desc);

create table public.lsac_content_modules (
  id bigint generated by default as identity primary key,
  module_id text not null unique,
  module_name text,
  module_type text,
  description text,
  admin_date timestamptz,
  vendor_name text,
  source_filename text,
  imported_at timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb
);

create table public.lsac_content_sections (
  id bigint generated by default as identity primary key,
  module_id text not null references public.lsac_content_modules (module_id) on delete cascade,
  section_id text not null,
  section_order int,
  section_name text,
  directions text,
  has_grouped_items boolean,
  item_count int,
  raw_payload jsonb not null default '{}'::jsonb,
  unique (module_id, section_id)
);

create table public.lsac_content_items (
  id bigint generated by default as identity primary key,
  module_id text not null references public.lsac_content_modules (module_id) on delete cascade,
  section_id text not null,
  item_id text not null,
  item_position int,
  group_id text,
  stem_text text,
  stimulus_text text,
  correct_answer text,
  options jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  unique (module_id, section_id, item_id)
);

create index lsac_content_sections_module_id_idx
  on public.lsac_content_sections (module_id);
create index lsac_content_items_module_id_idx
  on public.lsac_content_items (module_id);
create index lsac_content_items_section_id_idx
  on public.lsac_content_items (section_id);

alter table public.lsac_student_snapshots enable row level security;
alter table public.lsac_test_instances enable row level security;
alter table public.lsac_log_events enable row level security;
alter table public.lsac_content_modules enable row level security;
alter table public.lsac_content_sections enable row level security;
alter table public.lsac_content_items enable row level security;

create policy "lsac_student_snapshots_select_own"
  on public.lsac_student_snapshots
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "lsac_test_instances_select_own"
  on public.lsac_test_instances
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "lsac_log_events_select_own"
  on public.lsac_log_events
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "lsac_content_modules_select_authenticated"
  on public.lsac_content_modules
  for select
  to authenticated
  using (true);

create policy "lsac_content_sections_select_authenticated"
  on public.lsac_content_sections
  for select
  to authenticated
  using (true);

create policy "lsac_content_items_select_authenticated"
  on public.lsac_content_items
  for select
  to authenticated
  using (true);
